version: '3'

services:
  cron-redis:
    image: redis
    ports:
      - '6379:6379'

  application-1:
    build: 
      context: .
    ports:
      - '8080:8080'
    environment:
      REDIS_ADDRESS: cron-redis:6379

  application-2:
    build: 
      context: .
    ports:
      - '8081:8080'
    environment:
      REDIS_ADDRESS: cron-redis:6379